# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFilterBox(object):
    def setupUi(self, addFilterBox):
        addFilterBox.setObjectName("addFilterBox")
        addFilterBox.resize(400, 205)
        self.filterBox = QtWidgets.QDialogButtonBox(addFilterBox)
        self.filterBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.filterBox.setOrientation(QtCore.Qt.Horizontal)
        self.filterBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.filterBox.setObjectName("filterBox")
        self.label = QtWidgets.QLabel(addFilterBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(addFilterBox)
        self.filterBox.accepted.connect(addFilterBox.accept) # type: ignore
        self.filterBox.rejected.connect(addFilterBox.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addFilterBox)

    def retranslateUi(self, addFilterBox):
        _translate = QtCore.QCoreApplication.translate
        addFilterBox.setWindowTitle(_translate("addFilterBox", "Dialog"))
        self.label.setText(_translate("addFilterBox", "过滤"))
