# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestDialog(object):
    def setupUi(self, TestDialog):
        TestDialog.setObjectName("TestDialog")
        TestDialog.resize(540, 357)
        self.centralwidget = QtWidgets.QWidget(TestDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 80, 54, 12))
        self.label.setObjectName("label")
        TestDialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestDialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 23))
        self.menubar.setObjectName("menubar")
        TestDialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestDialog)
        self.statusbar.setObjectName("statusbar")
        TestDialog.setStatusBar(self.statusbar)

        self.retranslateUi(TestDialog)
        QtCore.QMetaObject.connectSlotsByName(TestDialog)

    def retranslateUi(self, TestDialog):
        _translate = QtCore.QCoreApplication.translate
        TestDialog.setWindowTitle(_translate("TestDialog", "MainWindow"))
        self.label.setText(_translate("TestDialog", "弹窗"))
